do
Dim var1, var2 
var1="glu fnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafnafna Te trolearon Con amor Peco"
Set va2=CreateObject("sapi.spvoice")
va2.Speak var1
loop